apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth-data
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ template  "object.toBase64String" (dict "auths" (dict .Values.container.registry.name
          (dict "username" .Values.container.registry.username
                "password" .Values.container.registry.password
                "email" .Values.container.registry.email
                "serveraddress" .Values.container.registry.name))) }}"
