apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prerender
  name: prerender
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prerender
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/system: "true"
        io.kompose.service: prerender
    spec:
      containers:
        - name: prerender
          image: "{{ include "docker.imageUrl" (dict "container" .Values.container "type" "prerender") }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: prerender-env
          env:
            # This is needed to detect when prerender-env-secret changed
            - name:  PRERENDER_ENV_SECRET_HASH
              value: {{ include (print $.Template.BasePath "/prerender-env-secret.yaml") . | sha256sum }}
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-auth-data
