apiVersion: v1
kind: Secret
metadata:
  name: prerender-env
type: Opaque
# noinspection SpellCheckingInspection
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ include "helper.secretValue" $value }}
  {{- end }}
