apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: data-dc-matchmaker
  name: data-dc-matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-dc-matchmaker
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/system: "true"
        io.kompose.service: data-dc-matchmaker
    spec:
      containers:
        - image: "{{ include "docker.imageUrl" (dict "container" .Values.container "type" "discord") }}"
          imagePullPolicy: Always
          name: matchmaker
          resources: {}
          envFrom:
            - secretRef:
                name: discord-matchmaker-env
          env:
            # This is needed to detect when discord-matchmaker-env changed
            - name: DISCORD_MATCHMAKER_ENV_SECRET_HASH
              value: {{ include (print $.Template.BasePath "/discord-matchmaker-env-secret.yaml") . | sha256sum }}
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-auth-data
