apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-cert
spec:
  secretName: backend-crt
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
  dnsNames:
    - "{{ .Values.hostnames.backend }}"
