apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    io.kompose.service: backend
spec:
  selector:
    io.kompose.service: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
