apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  annotations:
    cert-manager.io/issuer: "{{ .Values.certificate.issuerName }}"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`{{ .Values.hostnames.backend }}`)
      kind: Rule
      priority: 10
      services:
        - name: backend
          port: 80
      middlewares:
        - name: compress
          namespace: kube-system
  tls:
    secretName: backend-crt
    domains:
      - main: "{{ .Values.hostnames.backend }}"
