apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
  annotations:
    traefik.ingress.kubernetes.io/forwarding-headers: "X-Real-IP"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/system: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: "{{ include "docker.imageUrl" (dict "container" .Values.container "type" "frontend") }}"
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
          env:
            - name: PORT
              value: "80"
            # This is needed to detect when frontend-env changed
            - name: FRONTEND_ENV_SECRET_HASH
              value: {{ include (print $.Template.BasePath "/frontend-env-secret.yaml") . | sha256sum }}
          envFrom:
            - secretRef:
                name: frontend-env
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-auth-data
