apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
spec:
  secretName: frontend-crt
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
  dnsNames:
    - "{{ .Values.hostnames.frontend }}"
