apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    io.kompose.service: frontend
spec:
  selector:
    io.kompose.service: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
