apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: frontend-no-www-http
spec:
  redirectRegex:
    regex: "^http?://www\\.(.+)"
    replacement: "https://${1}"
    permanent: true

---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: frontend-no-www-https
spec:
  redirectRegex:
    regex: "^https?://www\\.(.+)"
    replacement: "https://${1}"
    permanent: true
