apiVersion: v1
kind: Service
metadata:
  name: socket
  labels:
    io.kompose.service: socket
spec:
  selector:
    io.kompose.service: socket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
