apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: socket
  annotations:
    traefik.ingress.kubernetes.io/forwarding-headers: "X-Real-IP"
  name: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: socket
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/system: "true"
        io.kompose.service: socket
    spec:
      containers:
        - image: "{{ include "docker.imageUrl" (dict "container" .Values.container "type" "socket") }}"
          imagePullPolicy: Always
          name: socket
          ports:
            - containerPort: 80
          resources: {}
          envFrom:
            - secretRef:
                name: backend-env
          env:
            - name: LARAVEL_WEBSOCKETS_HOST
              value: 127.0.0.1
            - name: LARAVEL_WEBSOCKETS_PORT
              value: "80"
            - name: LARAVEL_WEBSOCKETS_SCHEME
              value: 'http'
            # This is needed to detect when backend-env changed
            - name: BACKEND_ENV_SECRET_HASH
              value: {{ include (print $.Template.BasePath "/backend-env-secret.yaml") . | sha256sum }}
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-auth-data
