#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: redis-master-svc
spec:
  entryPoints:
    - redis
  routes:
    - match: HostSNI(`*`)
      services:
        - name: redis-master
          namespace: {{ .Release.Namespace }}
          port: 6379
