# Redeploy 2nd time if mongodb first time wasn't created
{{ if .Capabilities.APIVersions.Has "mongodbcommunity.mongodb.com/v1" -}}
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes:
        - SCRAM
        - SCRAM-SHA-1
  users:
    {{- range $user := .Values.users }}
    - name: {{ $user.name }}
      db: {{ $user.database }}
      passwordSecretRef:
        name: {{ $user.name }}-creds
      roles:
        - name: dbOwner
          db: {{ $user.database }}
        - name: clusterAdmin
          db: {{ $user.database }}
        - name: backup
          db: {{ $user.database }}
      scramCredentialsSecretName: {{ $user.name }}-scram
    {{- end }}
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
{{- end }}
