#file: noinspection KubernetesUnknownResourcesInspection
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongo-server-svc
spec:
  entryPoints:
    - mongodb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mongo-server-svc
          port: 27017
