# Bitnami Redis helm config
redis:

  replicaCount: 1

  image:
    registry: docker.io
    image: bitnami/redis
    tag: 7.2.5-debian-12-r0
    imagePullPolicy: Always

  service:
    type: ClusterIP
    port: 6379

  auth:
    enabled: true
    sentinel: false
    password: "{{ .Values.password }}"

  master:
    persistence:
      enabled: true
      storageClass: default
      accessMode: ReadWriteOnce
      size: 100Mi
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"

  replica:
    persistence:
      enabled: true
      storageClass: default
      accessMode: ReadWriteOnce
      size: 100Mi
    resources:
      requests:
        memory: "512Mi"
        cpu: "100m"

  global:
    storageClass: default
